### ISSUE TITLE
Unable to launch using workspace using domain name

### ISSUE THREAD

**Issue by naziris** [kasmtech/workspaces-issues#115]
I have a fresh install of Kasm under Debian 11.x on an esxi enviroment. I set my domain during the OS installatin and then replaced the crt and key under /opt/kasm/current/certs with my own. Even though the browser session to the UI is secured with my SSL Cert, I cant launch any workspace using my domain. Under Logs I see several hostname and proxy.
I.E:

```
host: proxy
ingest_date: 202201211659
application: kasm_agent
levelname: ERROR
message: Nginx reload failed (2022/01/21 16:59:55 [emerg] 120#120: host not found in upstream "sub.domain.com" in /etc/nginx/conf.d/containers.d/a959f4d3a72d860c455705a20e93483a243c3cde494735b2e3eefee0bd1363d3.conf:5 nginx: [emerg] host not found in upstream "sub.domain.com" in /etc/nginx/conf.d/containers.d/a959f4d3a72d860c455705a20e93483a243c3cde494735b2e3eefee0bd1363d3.conf:5 )
process: __main__.handler
```

If I try to launch a workspace though through IP, it works fine. Any ideas?

**Comment by mmcclaskey** [comment]
@naziris , the issue is that the kasm_proxy container, which is NGINX, must be able to resolve the hostname that the user comes in on. That may not happen because maybe the client is able to resolve the domain name but your server is not, due to split DNS or other configuration issues. There are two ways to fix it. The first, would be to ensure that your server is able to resolve the hostname with DNS (not a host entry, that will not work). The second option is to hard code the IP in Kasm's zone settings. See the following doc, the setting is "Upstream Auth Address", change that from the magic $request_host$ to the IP address of the server itself. The downside of this approach is that if you wanted to expand it to have multiple redundant servers, you would not want to hard code an IP.

https://kasmweb.com/docs/latest/guide/zones/deployment_zones.html#defining-zone-configurations

**Comment by naziris** [comment]
Thanks for replying @mmcclaskey.
Your second solution works. 
But I would like to give a shot to your first solution.
How can it resolve its own hostname via DNS and without involving /etc/hosts to set its own hostname.

**Comment by mmcclaskey** [comment]
That depends on your network architecture. Is the server behind a firewall with NAT and the server has a private IP? What DNS servers does the server point to, internal ones or public ones?

**Comment by naziris** [comment]
I have an internal DNS Server.
If I nslookup kasm.domain.com internalDNSIP it resolves Kasm IP

The issue here is that how the Kasm machine resolve its self from DNS. I mean it already knows its IP cause its under /etc/hosts

**Comment by mmcclaskey** [comment]
Docker does not pass host entries on the server to the inside of containers, so no... it does not know.

**Comment by naziris** [comment]
> Docker does not pass host entries on the server to the inside of containers, so no... it does not know.

Thanks a lot @mmcclaskey for clarifying that. Now I got the point of what you said earlier.
What's the best approach to solve this issue? 
From what I understand, my custom DNS IP has to be hard-coded somewhere?

**Comment by mmcclaskey** [comment]
If you have split DNS, public DNS for clients and internal DNS for servers inside your network (Kasm), then you will need to add a DNS entry in your internal DNS servers for Kasm. However, you stated that you had an internal DNS server and it does resolve already. nslookup ignores your /etc/hosts file, so if it resolves from the server itself, you should be good. 

If the IP address of Kasm will not change and you never plan to deploy Kasm in a multi-server architecture with two API servers, then you can just use the setup you have now with the IP address configured in the zone settings.
