### ISSUE TITLE
RDesktop Connection Arguments

### ISSUE THREAD

**Issue by ryanparsons7** [kasmtech/workspaces-issues#129]
Hi, I've been looking at using the rdesktop image to create RDP sessions to an internal host.
Image: https://hub.docker.com/r/kasmweb/rdesktop

However, I've not been able to figure out how to modify this image's configuration to auto-connect to a specific host, only opening the session to rdesktop and the session being empty with just the kasm logo in the background.

I've tried adding the following into the "Docker Run Config Override" but to no success:
{"environment":{"APP_ARGS":"192.168.1.4"}}

Thanks.

**Comment by j-travis** [comment]
The structure of your Docker Run Config Override is correct.

A challenge you may be facing is that rdesktop doesnt spit any errors visible to the screen, so you won't really know what the issue is.

Here are some steps to help you troubleshoot.
While the session container is running...

1. Get the ID of the container

```
sudo docker ps | grep rdesktop
```

2. Exec into the container

```
sudo docker exec -it <container id> bash
```

3. Then try to run `rdesktop`

```
rdesktop <server address>
```


You may also consider using Remmina https://hub.docker.com/r/kasmweb/remmina 
Your Docker Run Config might look something like this.

```
{"environment":{"APP_ARGS":"-c rdp://192.168.1.4"}}
```
