### ISSUE TITLE
Will Kasm do this?

### ISSUE THREAD

**Issue by myxr6turbo** [kasmtech/workspaces-issues#144]
We currently run one of the largest Citrix infrastructures in the education sector in Victoria and I recently saw a video on youtube by “Network Chuck” that reviewed/installed your software and I’m wondering if Kasm is something we could potentially migrate over to?

We currently use Citrix for our students in our BYOD program. Students have the option to either run an individual application or run a complete desktop. We also use Stratodesk on our Raspberry pi’s in the college for students for a full desktop experience in our computer labs.

The software we currently use is:
Adobe suite
Microsoft Office 2016
Google Sketch up
Sibelius
Python
ReadCloud
Sphero Edu
VLC
Google Chrome
Papercut (which we need for printing)

Could Kasm be a valid option for us to migrate over to with the above software mentioned?

**Comment by j-travis** [comment]
Hello,
I recommend you reach out to our team at the following link and we can discuss your use case and requirements.
https://kasmweb.com/about_us.html#contact

**Comment by myxr6turbo** [comment]
Thanks, I did email info@kasmweb.com regarding the above questing on the 24/1/2022 and I had no reply.

Thanks again,

**Comment by j-travis** [comment]
I show we replied on the 25th.  Hopefully we didnt end up in your spam folder. I'll have someone reach out to you again.

Kasm Workspaces currently only supports Linux desktops. Thats because the entire platform runs in docker containers. While there are Windows docker containers, they don't allow you to run graphical applications or desktop environments inside them.

So basically, if you need Windows desktops or apps that only run on Windows, Kasm will not be a good fit.  At the top of your list I see Adobe Suite and Office 2016- those won't be compatible.

**Comment by myxr6turbo** [comment]
Thanks for reaching out. I'll check the spam folder. 

Thanks again for your help.
