### ISSUE TITLE
Https problem

### ISSUE THREAD

**Issue by Laith1980** [kasmtech/workspaces-issues#168]
my web browser gives the error that Kasem is not safe. on the "https" is a stripe with red line.
any idia?

**Comment by j-travis** [comment]
When Kasm installs, it generates self-signed certificates. These certificates are not trusted by your browser, thus the security warning.

In order to remove that warning, you will need to generate certificates trusted by your browser. There are numerous ways to do this, but a cheap and easy way is to use letsencrypt.

Once you do that you can replace the self-signed certs Kasm created by following this documentation:

https://kasmweb.com/docs/latest/how_to/certificates.html
