### ISSUE TITLE
User accounts do not have sound active for Kasm - Admin accounts have sound 

### ISSUE THREAD

**Issue by rkz9000** [kasmtech/workspaces-issues#226]
The install works well in initial testing with Admin accounts, but default user account and any user account created does not have sound active.  Can you tell me how to fix this?  Thanks.

**Comment by j-travis** [comment]
This is due to the default Group Settings in Workspaces 1.10. 

The Administrators group has many of the permissions enabled, where the default users group does not. You'll have to add the permissions (Group Settings) you want your users to have.

- https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s
- https://kasmweb.com/docs/latest/guide/groups/group_settings.html

**Comment by rkz9000** [comment]
Found it!  Thank you.  You have built a pretty amazing product.
