### ISSUE TITLE
adding more disk capacity to KASM Workspaces 

### ISSUE THREAD

**Issue by TheUnSeen1** [kasmtech/workspaces-issues#236]
is there a way to add more disk capacity to KASM ? I am already out of space despite not adding anything new and deleting some images that I don't plan on using 

is there a way to reclaim space?

**Comment by mmcclaskey** [comment]
You can crank up auto pruning to aggressive and it will auto delete docker images that are not defined. The default setting of normal only auto deletes untagged old images. If your disk is completely full or nearly full, it won't be able to delete any images at all. You will need to free some disk space so that Kasm has the ability to auto delete images. 
https://kasmweb.com/docs/latest/guide/agent_settings.html#agent-settings

**Comment by TheUnSeen1** [comment]
is there a way to add more disk space? I've been looking and haven't been able to find an option in any of the guides

**Comment by TheUnSeen1** [comment]
Thank you for replying as well !

**Comment by mmcclaskey** [comment]
Adding more disk space is a question about general Linux server administration and not specific to Kasm. There are too many factors and different systems, volume formats, VMs, disk types, etc. Generally speaking, yes, you can either resize your volume or add a new volume and move things around.
