### ISSUE TITLE
Kali Linux session and networking disabled

### ISSUE THREAD

**Issue by hsemes** [kasmtech/workspaces-issues#249]
Networking grayed out in Kali. Anyone know how to enable this. Hit me up thanks.

**Comment by thelamer** [comment]
This is expected behavior.
Keep in mind this is a Docker container and Docker manages the networking. The Kali image can be useful due to the tools installed on it for pen testing, but when it comes to network layer things like sniffing, injection, or packet inspection you are still tied to your host's kernel and most of those features will not function with a genkernel. 

The greyed out icon you see is a default panel icon and depends on network-manager to function which cannot run inside a docker container unless it is privileged (even then it would cause many conflicts). 
If you are looking for your ip information try `ifconfig` or `ip` commands. If you need to setup a VPN try a CLI methodology for openvpn etc, or take a look at our documentation on using a sidecar container that can be attached to any of our images: 
https://www.kasmweb.com/docs/latest/how_to/vpn_sidecar.html
