### ISSUE TITLE
Standalone Thunderbird no user and persist config

### ISSUE THREAD

**Issue by UnleashSpirit** [kasmtech/workspaces-issues#257]
Hello, 
I'm lookig for help and "Community support" brings me here :)

I was searching a solution to group mailbox in a unique point and found your thunderbird solution as standalone docker.
It works great and fits my needs !

I was wondering if it's possible to remove id/password connection at begining, the kasm_user/password and allow kind of anonymous connection.
And more important, how can I persist the thunderbird config when docker restart ?

**Comment by j-travis** [comment]
Workspaces has a feature called Session Casting. It allows you to configure special URLs that when visited, automatically open a session. These can also be configured to be unauthenticated via the **Allow Anonymous** options. 

https://kasmweb.com/docs/latest/guide/casting.html?highlight=anonymous

Workspaces also supports Single Sign On via SAML and OIDC which may also work well for you.

It sounds like you want all users to access a single shared mailbox. In this case you probably want to create a custom image  that has your mailbox configurations baked in.

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://www.youtube.com/watch?v=BGP69_f1wq

Workspaces does support Persistent Profiles which would be helpful here , but thats only helpful if your users are authenticated because profiles are unique per user.
- https://kasmweb.com/docs/latest/how_to/persistent_profiles.html
- https://www.youtube.com/watch?v=teJSUxKEbfE&t=414s
