### ISSUE TITLE
VM - Installing Kasm errors 

### ISSUE THREAD

**Issue by macattack003** [kasmtech/workspaces-issues#258]
Virtualbox  6.1.38- Ubuntu 20.04.3 LTS Server Image 
8GB Ram
2 vCPUs
80GB HHD space 
Followed the commands from tutorial on youtube from Networkchuck as well as referencing your 
https://www.kasmweb.com/docs/latest/install/single_server_install.html

This is the warning I've received and I even deleted the VM and started fresh thinking I messed something up - I got no errors when running all the commands from the website.

`sudo dd if=/dev/zero bs=1M count=1024 of=/mnt/1GiB.swap
sudo chmod 600 /mnt/1GiB.swap
sudo mkswap /mnt/1GiB.swap
sudo swapon /mnt/1GiB.swap
echo '/mnt/1GiB.swap swap swap defaults 0 0' | sudo tee -a /etc/fstab
cd /tmp
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.11.0.18142e.tar.gz
tar -xf kasm_release*.tar.gz
sudo bash kasm_release/install.sh`

WARNING: No swap limit support Not enough disk space for the installation - Please free up disk space or use -I to not preseed images

Not sure if there is a bad command or something wrong with the tutorial being a bit dated so thats why I referenced your webpage directly and still not having any luck getting this working.

**Comment by j-travis** [comment]
The installer is looking for 50GB of free space on to root docker volume ( `/var/lib/docker`) by default.

You can run `df` to see how your drive space is allocated.  When installing Ubuntu 20.04 LTS , it may break up the drive space into multiple volumes by default, unless you tell it otherwise. 

This may be your issue.

If you run `--help` on the installer you can see there are additional flags . `--no-check-disk`  can be used to skip the disk check.

You can also change the list of default images that are installed. You can see this post for details

https://www.reddit.com/r/kasmweb/comments/w2bdi9/comment/igqj8dq/

**Comment by macattack003** [comment]
Is there instructions on how the partition should be setup during the
Ubuntu installation? I used the defaults so I'm assuming this is what is
causing the problem just not to sure how to fix it.

The only steps I followed regarding partitions is for the swap from the
site.

I will review the other information you sent about the images.

**Comment by j-travis** [comment]
This is an LVM thing that occurs when you first install ubuntu, so I cant help directly. But you may find this post helpful from another user: https://github.com/kasmtech/workspaces-issues/issues/135#issuecomment-1026171993
