### ISSUE TITLE
Installation error "Detected version of Docker is installed via snap. This is unsupported."

### ISSUE THREAD

**Issue by Gerben-Tx** [kasmtech/workspaces-issues#280]
I have Docker install through snap, apparently this is not supported by Kasm workspaces because i get this error after running the `install.sh` script

```
Detected version of Docker is installed via snap. This is unsupported.
Aborting Kasm Workspaces install.
```

My question is, why is this not supported and what are ways i can make this work without removing my whole docker?

**Comment by j-travis** [comment]
One of our containers needs to be able to puppet docker itself in order to create session containers , docker networks, map in data etc. This doesn't work with the snap version of the Docker which is why we go through the trouble of detecting it and aborting the install.

Sorry, but you'll need to run Kasm on another machine. The installer will install a compatible version of docker if one is not installed.

Hope this helps
