### ISSUE TITLE
Disk space suddenly full.

### ISSUE THREAD

**Issue by HeartBtz** [kasmtech/workspaces-issues#283]
Hello,
 I recently installed a KASMweb server, and I'm not sure how it works, I nevertheless explored what I could.

I assigned 70GB of disk to the VM that manages KASMweb, and this afternoon I observed a sudden explosion of disk space.
I can't understand why, at 1am today, all of a sudden, my disk filled up with nearly 30GB, for no apparent reason. Thanks :)
![image](https://user-images.githubusercontent.com/67628834/200869499-01f92ed6-d803-405f-bb0b-f92012cd51cd.png)
![image](https://user-images.githubusercontent.com/67628834/200869609-e8f3a4a3-5b3d-4542-a270-0052cbc18281.png)

**Comment by j-travis** [comment]
Hello,

How did you install Workspaces - Did you install using the instructions in our docs: (https://kasmweb.com/docs/latest/install/single_server_install.html) , or from somewhere else.

Can you show the results of the following command

```
sudo docker images
sudo docker ps -a
```

**Comment by HeartBtz** [comment]
Hello ! I installed with your guide :) 

![image](https://user-images.githubusercontent.com/67628834/200872503-399e574c-1cc1-45c9-b32d-a5483b2dfcdc.png)
![image](https://user-images.githubusercontent.com/67628834/200872666-622a9d97-f858-43c7-8fa1-7d718134035b.png)

**Comment by j-travis** [comment]
Ok,
Well generally speaking the minimum system requirements for a standard Workspaces install is 50GB, largely because our default enabled set of images needs that amount of space.

https://kasmweb.com/docs/latest/install/system_requirements.html?#resource-requirements

I see you've also enabled Kali (which isnt enabled by default) which itself requires another 10GB)

So, overall the disk usage seen is in line with what is expected.


I can't say what caused the system to only start pulling images at that time... maybe a network outage or something? You could look at the logs to see if the kasm_agent was previously reporting errors when trying to pull images.  Typically all the images are pulled at install time unless you tell it to defer until later. And of course if you add/enable more later it will pull again at that time.

**Comment by HeartBtz** [comment]
Heyo ! Thanks to your answer.
Indeed, in the logs there are errors in the pull. 
Is there a way to make a manual pull? 
You should also know that a few hours after this sudden rise (at the time I wrote the ticket), the storage suddenly returned to its normal state, as if it had emptied. 
Would you have a guide to running manual pushes, or manual dockerprune directly on kasm? 
Thanks for your help!
![image](https://user-images.githubusercontent.com/67628834/200919197-6b89aaaf-0166-4351-be3b-430567b24c31.png)

**Comment by j-travis** [comment]
If you remove the docker registry from the images definitions within workspaces it will not attempt to pull the images. 

You can then pull them manually from the command line like you would any other docker image
.

There is an automatic pruning system within the platform you can turn on/off per your desires.
https://kasmweb.com/docs/latest/guide/agent_settings.html#agent-settings
