### ISSUE TITLE
password for KASM-USER

### ISSUE THREAD

**Issue by 7069wrk** [kasmtech/workspaces-issues#297]
I have fired up a handful of linux machines today and all of them want the password for a kasm-user or kasm_user.   i have tried the credentials created during build, and the one listed on the web and with some of the containers.  `password` is not working.

can someone tell me where to find the kasm-user password for say ubuntu-core, kali-core, tracelabs-core... ?

**Comment by mmcclaskey** [comment]
If you are trying to run a container directly, without Kasm Workspaces, see the README here https://github.com/kasmtech/workspaces-images

Per the readme, you need to set the VNC password via an environmental variable called VNC_PW. 
`sudo docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/firefox:dev`

**Comment by 7069wrk** [comment]
actually within KASM. while in there try to run sudo and it asks for password. 

it isnt 'empty' nor 'password' nor anything in the credentials list, and wasnt prompter to set any.

i did set the {"user":"root"} and though that lets me run update - of course i lose everything on reboot - so not sure it really matters.

i love the tech. i will keep working on it. may just need to create my own images. 

if there is somehting im missing please feel free to let me know. i am new to all this and unashamed of making mistakes.

**Comment by djdanielsson** [comment]
so to be clear, there is no way to make sudo work and the only way to get root access is by running the whole image as user root?

**Comment by j-travis** [comment]
sudo is not installed on most images, and the few that it is (kali) there is no root password configured. 

So you can either run the container as root, or install/configure sudo yourself.
You can do this by building your own custom image
https://kasmweb.com/docs/latest/how_to/running_as_root.html#building-a-workspace-with-sudo

or using Docker exec:

https://github.com/kasmtech/workspaces-issues/issues/222#issuecomment-1169233182
https://kasmweb.com/docs/latest/guide/workspaces.html#docker-exec-config

**Comment by bxtux** [comment]
Hello, my workaround : edit /etc/passwd file with docker file manager.  Delete the "X" after kasm-user:: (let nothing between the two nexts ":"), edit the sudoer file in the same directory and add " kasm-user ALL=(ALL:ALL) ALL " ..; Now the password is empty and you can do a passwd to set a new password, and sudo su.

**Comment by Ahson-Shaikh** [comment]
@

> Hello, my workaround : edit /etc/passwd file with docker file manager. Delete the "X" after kasm-user:: (let nothing between the two nexts ":"), edit the sudoer file in the same directory and add " kasm-user ALL=(ALL:ALL) ALL " ..; Now the password is empty and you can do a passwd to set a new password, and sudo su.

This doesn't work. To edit the file, you still require sudo permissions. And so the password for the sudoer.

**Comment by bxtux** [comment]
> @Ahson-Shaikh ....Well It Works for me, because when you use the Docker File Manager toi have an direct acces to the filesystem as Root....  And if kasm user Is sudoer with à blank password, just need to set à New password ans do sudo su... Et voilà... Juste try it
> 
> > Hello, my workaround : edit /etc/passwd file with docker file manager. Delete the "X" after kasm-user:: (let nothing between the two nexts ":"), edit the sudoer file in the same directory and add " kasm-user ALL=(ALL:ALL) ALL " ..; Now the password is empty and you can do a passwd to set a new password, and sudo su.
> 
> This doesn't work. To edit the file, you still require sudo permissions. And so the password for the sudoer.

**Comment by CarbonMac** [comment]
> Hello, my workaround : edit /etc/passwd file with docker file manager. Delete the "X" after kasm-user:: (let nothing between the two nexts ":"), edit the sudoer file in the same directory and add " kasm-user ALL=(ALL:ALL) ALL " ..; Now the password is empty and you can do a passwd to set a new password, and sudo su.

Okay, so, you should have your workspaces in a folder where you can access the data (even if using a hypervisor). I personally run in proxmox LXC with lsio kasm in docker. This allows me to already have access to the opt folder without needing anything fancy, but it does require some hoops to jump over. Since I run a slightly non-vanilla setup, YMMV.



**With the container running inside kasm you want to edit**:
- `docker exec -it kasm bash` or however you get a shell inside your kasm setup
- You need to perform a `docker inspect` of the container you're trying to add a password to, this will give you a field looking vaguely like this in the output:
```
"MergedDir": "/opt/docker/overlay2/feeef7499120a5a840343915229a9d00ebc4355bc98561187ffd237b8322a148/merged",
```
- cd to the MergedDir above
- copy the necessary file(s) `$MergedDir/etc/shadow` and `$MergedDir/etc/passwd` one layer above inside the kasm container.
- On your docker/HV host, cd to the local mount and/or the docker volume that contains the passwd and shadow (you will not be able to see the merged dir on the host in most circumstances if docker) you will need to be root to do this
- Edit them as root according to the above instructions, `Delete the "X" after kasm-user:: (let nothing between the two nexts ":"), edit the sudoer file in the same directory and add " kasm-user ALL=(ALL:ALL) ALL "` (sudoers may complain about being read only `:wq!` it like a boss!)
- In the kasm container where you just were, copy the edited files back into the merged dir
- Set a passwd on the kasm-user in the terminal
- Enjoy!
