### ISSUE TITLE
Help needed - http, domain conceting

### ISSUE THREAD

**Issue by karilca** [kasmtech/workspaces-issues#312]
I need help with kasm workspace, but i installed successfully and I can aces it trough web brower in https. I wolud want to know if I can acces kasm workspace trough http if not i wolud also like to know how to connect my domain managde by cloudflare with ​kasm workspace.

Happy new year!

My setup: pc intel i3 with grapich, 120gb ssd, 500gb hdd, debian 11
Sorry i'm not native english speaker.

**Comment by j-travis** [comment]
Hi,
You cannot access Workspaces over http , only https because we use certain browser features that only work over https.

Hosting services on public domain and via cloudflare is not something we can directly help with but the community has several guides you may find helpful.

https://www.reddit.com/r/kasmweb/comments/zsswhn/db_tech_add_google_github_and_other_access/

You may find our general guides on using a reverse proxy and replacing the self signed certs helpful along the way. They may or may not apply depending on the route you take:

- https://kasmweb.com/docs/latest/how_to/reverse_proxy.html
- https://kasmweb.com/docs/latest/how_to/certificates.html
