### ISSUE TITLE
Question: Do all electron apps need `--no-sandbox` option?

### ISSUE THREAD

**Issue by serpro69** [kasmtech/workspaces-issues#322]
I've been trying to install and run an electron app in an ubuntu-jammy-desktop container, and it seems that I can only run the application if I add the `--no-sandbox` option, otherwise I'm getting "operation not permitted" error.

Looking at some custom scripts, I can see the same is used for other electron-based apps like [atom](https://github.com/kasmtech/workspaces-images/blob/c8d68b593d033f671bcee3a559b2b24fbd2065ba/src/ubuntu/install/atom/custom_startup.sh#L3) or [vs-code](https://github.com/kasmtech/workspaces-images/blob/c8d68b593d033f671bcee3a559b2b24fbd2065ba/src/ubuntu/install/vs_code/custom_startup.sh#L8).

I've also searched [kasm documentation](https://kasmweb.com/docs/latest/index.html) and it has no mention of why this option is needed, although it looks like it is "mandatory" in a sense. This includes the [building custom images](https://kasmweb.com/docs/latest/how_to/building_images.html) docs, which actually use "atom" in an example, but don't mention that this option is needed to run it.

I'm not very familiar with developing electron apps, but the electron [documentation](https://www.electronjs.org/docs/latest/api/command-line-switches#--no-sandbox) mentions that `--no-sandbox` option is recommended only for testing purposes. So I'm wondering if there are any "risks" or other implications of always running these apps with `--no-sandbox`. And if there're any workarounds to run electron apps w/o `--no-sandbox` option?

**Comment by j-travis** [comment]
Most, if not all probably do. 
Over time we've noticed that it changes per app. I suspect it's something to do with what features are enabled or the default build/run flags used by the developer.

Our example "building custom images doc" does not use atom or another electron app. It uses sublime text so it's not applicable there.
 
The electron/chrome sandbox does not run correctly inside a docker container with standard privileges, largely because to operate the sandbox the process needs to first have elevated privileges within the container for the process to enable its own sandbox protections...some of which are the similar protections offered by the standard docker container. So, yes, there is some risk.

If you'd like to try and run with the sandbox, you'll need to identify which permissions need to be enabled and adjust the container's [Runtime privileges and Linux capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) and perhaps the [Security Configurations](https://docs.docker.com/engine/reference/run/#security-configuration).  Once you figure out what those, you should be able to map those policies inside of Workspaces via the [Docker Run Config Override](https://kasmweb.com/docs/latest/guide/workspaces.html#docker-run-config)

**Comment by serpro69** [comment]
Oh right, the example uses sublime, that was my mistake :)

I will try to experiment a bit with this and see if I find a solution. Thanks for such a thorough explanation and links @j-travis !
