### ISSUE TITLE
Paid Kasm Cloud Destop service has stopped accessing chatgpt (screenshot attached)

### ISSUE THREAD

**Issue by HarrisKirk** [kasmtech/workspaces-issues#334]
**Describe the bug**
I launched a Chrome browser and navigated to https://chat.openai.com/auth/login

**To Reproduce**
1. Click on the Chrome Browser in the 'kasm disposables' service I have.
2. Navigate to https://chat.openai.com/auth/login
3. See error in screenshot

**Screenshots**

![kasm-screen](https://user-images.githubusercontent.com/2710359/220188920-4fabde81-b47a-4aa6-a00d-7f7af52b9453.png)

**Comment by j-travis** [comment]
Sorry, there is not much we can do about this.

The cloud personal service provisions sessions in Oracle Cloud. It likely openai has decided to block the IP space of oracle and potentially other cloud providers to hedge against abuse.  

We can't control what openai or any other site does in this regard.

Consider opening a support request with openai. This is speculation, but its possible they decided to block all oracle ip space because AFAIK there is no first party vdi service offered by them. Whereas AWS has AWS Workspaces which may impact their decision to allow/deny traffic from different cloud providers.  I'm not saying it works from AWS - I've not tested - just offering an idea as to why things might be treated differently if indeed they are.

**Comment by HarrisKirk** [comment]
Ok, thank you for the well-thought-out reply.    I am wondering if this blockage is common or is it unique to OpenAI.  Interesting times we live in.  Again, thank you for your Kasm cloud offerings and you response.

**Comment by j-travis** [comment]
Its not unheard of, but we don't get too many reports like this.

While I wont name names, typically we've noticed that more inexpensive cloud providers get blocked more often because, by the nature of them being cheap, they attract more folks that will use them for nefarious purposes. That leads to their IP space getting a bad reputation and thus blocked more often.

ChatGPT is arguably the most popular/disruptive technology released in the last year and is exploding in popularity. So certainly, they are facing challenges with scaling , and are working on monetizing the platform. With all the extra attention, there are probably plenty of people trying to probe it / script it etc. So, its not surprising for them to be aggressive and block access to minimize headaches. 

While unfortunate for our users, its somewhat understandable.

**Comment by 3kh0** [comment]
For me, I have my server on linode, I had to use a VPN, but when I got ChatGPT Plus, I did not need it anymore, quite weird.

![image](https://user-images.githubusercontent.com/58097612/220649176-71f8e93b-bfd9-4fbf-9f81-68b38fb5b26e.png)
