### ISSUE TITLE
Port Forwarding 

### ISSUE THREAD

**Issue by rxerium** [kasmtech/workspaces-issues#345]
Hi there,

More of a question than a bug report/feature request.

Is it possible to port forward specific ports from a ubuntu server to the internet if I'm hosting a KASM instance in the cloud? If so, how can this be achieved? 

Many thanks,

Rishi

**Comment by j-travis** [comment]
I'm sorry, 
I don't quite understand what you are asking and don't want to incorrectly assume. Can you provide more detail about what you are wanting to do

**Comment by rxerium** [comment]
So I'm looking to spin up disposable Ubuntu 22.04 containers for vulnerability testing. For example, I could create a vulnerable Apache instance within the Ubuntu 22.04 KASM container, when I set this up I'd like to test my vulnerability scanner against this container and currently I can only do this over the local network. I was wondering if its possible to access/scan my Apache webserver using the public IP/port of my KASM workspaces instance? So instead of scanning the web server with a local IP (192.168.1.2:8080) I would use the public IP of the server (23.21.54.45:8080). Hope this makes sense :)

**Comment by j-travis** [comment]
Kasm doesn't directly provide the ability to publish arbitrary ports.

You may look into using something like tailscale to build a mesh VPN network between Kasm and your scanner. We have guides for running the entire [Kasm server in tailscale](https://kasmweb.com/docs/latest/how_to/Tailscale.html), or connecting the session [containers to a tailscale sidecare vpn container](https://kasmweb.com/docs/latest/how_to/vpn_sidecar.html#option-3-tailscale) , but in this case you probably want to run tailscale directly in the session container so you can scan the vulnerable apache service running inside it.

Here are some tips to get you started.

# Tailscale Inside a Container

1. Build Image using the provided docker file below and register in Kasm. See [Docs](https://kasmweb.com/docs/latest/how_to/building_images.html) and [Video](https://www.youtube.com/watch?v=BGP69_f1wq0)

2. Use the following for the **Docker Run Config Override** section of the Image. [Docs](https://kasmweb.com/docs/latest/guide/workspaces.html#docker-run-config)

       {"devices":["/dev/net/tun","/dev/net/tun"]}
       
3. Use the following for the **Docker Exec Config** for the Image (Start tailscaled as root and  - notice the use of an [ephemeral auth key](https://tailscale.com/kb/1111/ephemeral-nodes/) so that the container can be auto connected to and removed from the tailscale network). You could also put these commands in a custom_startup script if you didnt want to use  the [Docker Exec Config](https://kasmweb.com/docs/latest/guide/workspaces.html#docker-exec-config). 

       {"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'tailscaled & tailscale up --authkey=tskey-abc123'"}}



Dockerfile
```
ARG BASE_TAG="1.12.0-rolling"
FROM kasmweb/ubuntu-focal-desktop:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Install Tailscale

RUN curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg |  apt-key add -
RUN curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list |  tee -a /etc/apt/sources.list.d/tailscale.list
RUN apt-get update && \
    apt-get install -y tailscale


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

```
