### ISSUE TITLE
[Bug] - Can't sign out of RDP connection

### ISSUE THREAD

**Issue by charlespick** [kasmtech/workspaces-issues#353]
**Describe the bug**
With all other RDP clients, when you sign out of the user or get disconnected for any reason except intermittent connectivity, the client closes. When you sign out of RDP in Kasm though, or you get disconnected due to timeout, or you get disconnected because you try connecting somewhere else, Kasm immediately reuses your credentials that were used to establish the original connection even if you don't have them saved. This means that if you forget to delete your kasm RDP connection, when you try to connect to the same server from somewhere else you're immediately kicked out. It also makes things like RDP session timeout with Group Policy ineffective. And you can never sign out the user in the RDP server. You can only delete the Kasm session which leaves the user logged in. 

**Expected behavior**
Kasm should just return to the home screen when the connection is terminated

**Workspaces Version**
1.12.0.d4fd8a

**Workspaces Installation Method**
Single Server

**Client Browser:**
Chrome, Safari

**Comment by mmcclaskey** [comment]
This behavior has been changed in 1.13.0, which is due to be released next week or as early as this week. In 1.13.0, Kasm will display a Session Closed screen, if the RDP connection was explicitly terminated by the server. This should cover scenarios such as the user logging out from inside Windows, the user's RDP session being taken over by another user, etc. Kasm should continue to automatically reconnect if the session was lost due to networking issues. 

You can run the developer preview today to confirm if you wish. https://kasmweb-build-artifacts.s3.amazonaws.com/kasm_backend/branches/develop/kasm_workspaces_develop.tar.gz

**Comment by charlespick** [comment]
just tested it and it does what you say! Can't wait!
