### ISSUE TITLE
Requesting clarity on session timeout behavior 

### ISSUE THREAD

**Issue by Lingomat** [kasmtech/workspaces-issues#380]
### Existing Resources

- [ x] Please search the existing issues for related items
- [ x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
Use case: Virtualised web browser session for performing anonymous academic research surveys (and opening other tabs as required). Our image is modified with a web archiver so we can see what people do.

We want to fairly quickly expire inactive sessions so they can be recycled for other participants. However session expiry is unpredictable. They expire fine when using the session_time_limit setting but here's what we're trying now and how we understand them from your documentation:
```
session_time_limit = 0 # no time limit, expire based on other settings
idle_disconnect = 5 # Idle for five minutes, user is logged out -> keep_alive_expiration_action
keepalive_interval = 60 # keep alive pings ? at 1-min intervals?
keepalive_expiration = 300 # After 5 minutes, since last ping -> keep_alive_expiration_action
keepalive_expiration_action = delete
```
These are applied for the all users group.

Sessions seem to be deleted after around 45 minutes. This has no relation to the values supplied above.

**Describe the solution you'd like**

We just want the containers to be deleted after appropriate timeout values. 

On the session view, what is Last Active purporting to be showing? It seems it's usually the same, but not exactly the same, as Uptime. How can someone be active if they are logged out?

**Describe alternatives you've considered**

Going back to session_time_limit. This works okay but we'd rather avoid an ominous timer of doom for survey participants.

**Comment by j-travis** [comment]
All of the session timers and their interplay are documented here: https://kasmweb.com/docs/latest/guide/groups/group_settings.html#session-time-limits

You likely don't want `session_time_limit` since its only meant for those overt self destruct use cases like demos where it will self destruct with our without user interaction at pre-determined time. Thats why the countdown is displayed.  Delete this group setting. Dont set it to 0 , just delete it from your group settings.

`idle_disconnect`, will disconnect the user from a running kasm session after this many minutes of inactively. activity being defined as mouse or keyboard movements.

While the user is connected to a kasm session , they will send a keepalive message at the defined `keepalive_interval`. Each of these messages extend the expiration of the session out based on the `keepalive_expiration` you have defined. 

Notably, once the user is disconnected, (or otherwise closes their browser) they no longer send the keepalives.

You'll also want to check to see if you have group settings layered on different groups. https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s

I recommend first verifying that the `idle_disconnect` is working as expected.. Try setting it to 1 minute so its easier to verify. Once the user is disconnected, you should be able to follow the other sequence of events through to deletion of the session

**Comment by Lingomat** [comment]
Thanks for your response. It seems like my understanding of the settings was okay.

I tested again with a single change, deleting `session_time_limit` instead of just setting it to 0 and the session was deleted in the time frame I expected from the session.

So it seems this is resolved, thank you Justin.
