### ISSUE TITLE
[Bug] - Unable to delete session after adding s3 mapping and persistent home location

### ISSUE THREAD

**Issue by lpn-cls** [kasmtech/workspaces-issues#449]
**Describe the bug**
Session does not get deleted and hangs indefinitely. Although the container is removed from the container host, it remains hung on the web end. Restarting the session or portal does not resolve the issue. The session seems to require manual removal from the external PostgreSQL server to be fully terminated.

**To Reproduce**
- Create a Fedora 38 desktop workspace.
- Add an S3 storage mapping.
- Enable a persistent home folder (s3://url).
- Attempt to delete the session via the Portal.

**Expected behavior**
Session should be deleted without any issues.

**Screenshots**
-

**Workspaces Version**
Workspace version: 1.14
Workspace: Fedora 38 desktop
Portal version: [specify version, if known]
Database: External PostgreSQL

**Workspaces Installation Method**
Multi-Server

**Client Browser (please complete the following information):**
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`-> Linux kasm 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`-> PRETTY_NAME="Ubuntu 22.04.3 LTS"
 - `sudo docker info` -> Version:    24.0.5
 - `sudo docker ps | grep kasm`

kasmweb/nginx:1.25.1     "/docker-entrypoint.…"   13 days ago   Up 4 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
kasmweb/share:1.14.0     "/bin/sh -c '/usr/bi…"   13 days ago   Up 4 hours (healthy)   8182/tcp                                        kasm_share
kasmweb/api:1.14.0       "/bin/sh -c '/usr/bi…"   13 days ago   Up 4 hours (healthy)   8080/tcp                                        kasm_api
kasmweb/manager:1.14.0   "/bin/sh -c '/usr/bi…"   13 days ago   Up 4 hours (healthy)   8181/tcp                                        kasm_manager

**Additional context**
This issue is consistent and occurs every time the above steps are followed.

**Comment by mmcclaskey** [comment]
This is most likely a configuration issue, and the docs don't do a good job of explaining this within the S3 profile section. When you have a multi-server deployment, you need to configure a few things, depending on what features you need, in order to get things all running. With S3 profiles, the workspaces containers need to make API calls to the API servers and to do that they need to know the hostname or IP address of your API server(s). With a single server deploy, this is automatic. But for a multi server deployment, things get complex. People can deploy kasm behind load balancers that can't be reach internally, for example, there is no shortage of architectures and we can't detect them.

Long story short, go into your Zone settings and change the Upstream Auth Address to the IP address or hostname of your API (Web App) server. This should be reachable by your agents and containers running on the agents. So if you use a hostname, it must be resolvable by these systems.

<img width="1001" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/5209269/9bb09fad-5572-4afe-8146-9dce330b34ba">

One last note. You should be able to force delete sessions as administrator. Go to the Sessions table in the Admin dashboard, find the session and delete. If the session was not already delete pending, you may have to do it a second time. If the Admin attempts to delete a session that is already pending a delete, it will force delete it.
