### ISSUE TITLE
Problem resolving some web pages

### ISSUE THREAD

**Issue by LLB1962** [kasmtech/workspaces-issues#460]
I had kasm installed on AWS in a docker container with kubernetes cluster running umbunto.  I had chrome in a container installed on kasm and all sites loaded perfectly on AWS.  I installed the exact same kasm setup as I had on AWS on two different hosting providers (dedicated servers) with more hardware resources than on AWS.  A few sites will not load on the two hosts unless I access the site from google search link and a few sites will not load from a google search link and also will not load by typing the URL in the address bar.  I have tried using a different DNS (Google public.)  No firewall is active.  Yahoo pings from kasm but will will not load when accessed from chrome.  No extensions are installed in chrome.  Any ideas why some sites will not load on the two different hosts and will load on AWS?

**Comment by j-travis** [comment]
Sorry, this isn't something we are going to be able to help with since it seems like an environment or custom setup issue.
Its common for some websites to block IP space they deem higher risk so maybe thats it?  Try using `curl` from the command line within the kasm container and outside (on the host) to see if you can identify if the problem only happens in kasm or out
