### ISSUE TITLE
[QUESTION]  How to use root user AND be able to use web browsers?

### ISSUE THREAD

**Issue by thefunkygibbon** [kasmtech/workspaces-issues#465]
Example,  I'm trying to use Kali.  It seems a fair few things need root access, least of which being apt-get to install tools which are not installed by default. 

I appriciate that you simply need to add 
{
    "hostname":"kasm",
    "user":"root"
}

to the config, and yes that works.. but it also seems to stop the webbrowser (firefox) from running at all. 

Question is, is there a way of being able to just simply use it as the root user (or at least being able to SU to root when needed, like any normal linux OS whilst not having any strange issues like FF not working etc?

Thanks
Apologies for posting this here, but I can't seem to find a discord server for KASM or any normal chat forums

**Comment by j-travis** [comment]
Instead of running as root you can configure sudo:
https://kasmweb.com/docs/latest/how_to/running_as_root.html#installing-and-configuring-sudo-via-docker-exec


Kali also includes Chromium which can run as root

**Comment by thefunkygibbon** [comment]
I have added 
{
 "first_launch":{
      "user":"root",
      "cmd":"bash -c 'apt-get update && apt-get install -y sudo && echo \"kasm-user  ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers'"
  }
}
to the Docker Exec Config part of the workspace on Kali and another but neither will load, i get a red message about it not working and to contact my admin.  ![image](https://github.com/kasmtech/workspaces-issues/assets/19172392/768aae08-e60a-402e-8878-49a1e713bbe5)

There doesn't appear to be anything particularly obvious in the logs either.

**Comment by thefunkygibbon** [comment]
cloned existing and ran again.  seems to have started up fine this time.  thanks :-)

**Comment by thefunkygibbon** [comment]
am i understanding this wrong?  I've updated (apt update) about 600 mb of updates for kali,  but when I start a new session , none of those updates have been stored from before.   persistent storage is enabled and working in that I have moved things on the desktop and created a test file and they have remained as I expected.  
am i wrong in thinking that more OS level changes would persist too?

**Comment by j-travis** [comment]
There are a couple ways to handle [Persistent Data](https://kasmweb.com/docs/latest/guide/persistent_data.html),  I assume you are referring to [Persistent Profiles](https://kasmweb.com/docs/latest/guide/persistent_data/persistent_profiles.html), which works by storing the users HOME directory outside of the container.  Its not the full disk of the container , literally only /home/kasm-user . This works well to preserve application settings, documents etc since by convention they typically store those items within the home directory. None of the persistent data options work for the full container disk.

If you install something with apt,  etc, usually none of that is stored within the home directory, so it will be lost when you end the session

Generally speaking you want to create a custom image with the software your users need ahead of time.

You can build one https://kasmweb.com/docs/latest/how_to/building_images.html , or create one from a running session : https://kasmweb.com/docs/latest/guide/sessions.html#create-image-from-session.

If you want to emulate a long lived disk , you can have the system, stop or pause your session instead of deleting it by adjusting the keepalive_expiration_action: https://kasmweb.com/docs/latest/guide/groups/group_settings.html#keepalive-expiration-action, but in general I don't recommend that  - instead spend a little time creating a custom image with the software you need.
