### ISSUE TITLE
kasm printer

### ISSUE THREAD

**Issue by zoransl** [kasmtech/workspaces-issues#523]
I installed KASM workspace on ubuntu 22.04. Within ubuntu under oracle vm I installed windows 11 pro. In workspace I've opened workzone and connected it to windows 11and it all works perfectly fine when I approach windows server. But, when I want to print any document, I choose KASM printer automatically windows session gets frozen. The only thing I can do is to enter control panel and delete session. Please advise how I can make KASM printer to work in windows session.

**Comment by j-travis** [comment]
Hello,
When you enter a bug ticket we asked you to provide a number of data points the help us understand your environment so that we have a starting point to troubleshoot.  Can you please provide these?

https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example
