### ISSUE TITLE
Problem with starting workspace n could not load resources 

### ISSUE THREAD

**Issue by CooperDActor-bytes** [kasmtech/workspaces-issues#544]
I have updated reinstalled and read guides nothing has worked

**Comment by j-travis** [comment]
When you put in a new issues we ask a number of questions. These details are neccesary for the community to have a shot at providing feedback. Otherwise there is nothing to go on 
https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example
