### ISSUE TITLE
Windows 10 Beta  / Cloud Instance Personal - App install / Persistance?

### ISSUE THREAD

**Issue by layer3host** [kasmtech/workspaces-issues#580]
Not a bug or feature request, General Query 

I assume that with the Windows 10 Beta Workspace available now in the Personal Cloud Subscription that...

1) it is not persistent - session tears down based on your plan, mine is 60m I think. 
2) can we pay extra to make it persistent, other than going with workspaces for business as I am just a single user
3) I also assume if I install a windows app, next session will be a fresh instance with only the default apps installed. 

Let me know - Thanks all! 

Dave

**Comment by j-travis** [comment]
1. Yes
2. No
3. Yes

Currently it is a free beta for a limited time. 

We will likely offer Windows based sessions in some sort of package on the Cloud Personal service. They likely will not have full persistence. And they likely will come add additional cost. The reality is it costs 5-10x more to run Windows VM sessions primarily due to Windows licensing  but also the performance characteristics  play a part. Naturally we will have to chare more for that.
