### ISSUE TITLE
Shortcuts not working in Kasm in other languages.

### ISSUE THREAD

**Issue by TaxiF-Kasm** [kasmtech/workspaces-issues#585]
Hello,

shortcuts are not working on all other languages other than english.

We have confirmed the issue from Kasm as if we connected to our servers via remote not kasm it works the shortcuts and we have gone all web for a fix we couldnt find.

thanks

**Comment by j-travis** [comment]
Hi,
When entering tickets we ask that you provide a baseline of information to help the community be oriented to your environment. (e.g OS, version, browser etc) otherwise we have no basis from witch to evaluate.
https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

Please provide as much detail as possible about your environment , language, the shortcuts you are using, keyboard layout etc. 

Otherwise we have nothing to go on.

I will close this until more information is provided
