### ISSUE TITLE
Default DNS settings

### ISSUE THREAD

**Issue by brettthomson** [kasmtech/workspaces-issues#599]
Hi - I have updated the DNS server my home network uses. All the currently installed workspaces etc are using the old DNS settings, which is fine for external resources, but internal servers and resources no longer resolve. How can I bulk update all previously installed workspaces using the old DNS.

Thanks for your help in advance.

**Comment by j-travis** [comment]
You can configure your container based workspace to use specific DNS servers by utilizing the Docker Run Config Override setting.
You can configure this at the Workspace level or the Group Level (e.g so that all workspaces spawned by that user get the settings)

Workspace level settings take priority over group settings though, so if you've already configured the old DNS settings at the Workspace level, you will need to modify or remove them at that level

https://kasmweb.com/docs/latest/how_to/custom_dns_servers.html
