### ISSUE TITLE
[Feature Request] - Client settings enabled by default?

### ISSUE THREAD

**Issue by MrMEEE** [kasmtech/workspaces-issues#601]
### Existing Resources

- [ X ] Please search the existing issues for related items
- [ X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
I want to know if it is possible to enable things like game mode and fullscreen by default for either specific users, or for all users?

**Comment by j-travis** [comment]
Sorry, it is not possible to enable fullscreen or gamemode by default

**Comment by mmcclaskey** [comment]
Due to browser security, some actions require a user driven event in javascript. Pointer lock (and game mode which uses pointer lock) is a browser feature that requires user interaction. In other words, the javascript that turns on pointer lock, must have been triggered by a user clicking on a button or something like that. This security protection keeps malicious apps from being able to hold a user hostage, constantly putting something full screen with pointer lock, unable to get out.
